name = "cloudflare-saas-starter"
compatibility_date = "2024-03-29"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "ledatabase"
database_id = "a00ed52b-0333-4c91-a02c-1fb6b2ddc5af"
